### ISSUE TITLE
Version 2 of conditional fields

### ISSUE THREAD

**Issue by alberto56** [tdjeunes/website#9]
Currently if you get the latest master branch and run docker compose up

then go to http://0.0.0.0:4000/admin/#/collections/pages_v3

Then create a new page

Then create a new section, you will have conditional fields based on the "hints", for example:

in ./docs/_includes/decap/parts/sections.yml

we have this code:

```
        fields:
        - label: 'Structure'
          name: 'structure'
          widget: 'select'
          options:
          - { label: 'Breadcrumb', value: 'breadcrumb' }
          - { label: 'Message', value: 'message' }
          - { label: 'Image and content', value: 'image_content' }
          - { label: 'Content and image', value: 'content_image' }
          - { label: 'Status', value: 'status' }
          - { label: 'Collage', value: 'collage' }
{% for block in site.categories.jekyll_visualblocktypes %}
          - { label: '{{ block.label }}', value: '{{ block.title }}' }
{% endfor %}
        - { label: 'Message', name: 'message', widget: 'string', required: false, hint: 'some text [only:message]' }
        - { label: 'Type', name: 'type', widget: 'string', required: false, hint: 'type of message, e.g. "info", "warning", "error" [only:message]' }
```

Because Message and type have [only:message] in their hints, they will be displayed conditionally only for messages.

This system works but as we add structures, it gets unwieldy. I would like to change this so that:

* we no longer use the value of hints
* we use the json data instead
* to see the json data, go to http://0.0.0.0:4000/admin/#/collections/pages_v3
* make sure you hare logged in

Open the console and type in "types"

You should see this:

![Image](https://github.com/user-attachments/assets/82479f30-008d-4733-ba10-aa75dc53b22f)

Now instead of using the hints, your code should use that "types" structure.

For example, because the type "onlytext" requires "content", all other fields should be hidden if "onlytext" is selected.

![Image](https://github.com/user-attachments/assets/309051ee-c1f8-4a1c-801d-164fee241085)

If a structure which is *not in types* is selected, then show everything. (Eventually I will get them all in types)
